# Generated by Django 5.2.3 on 2025-06-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=100)),
                ('Middle_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Date_of_Birth', models.DateField()),
                ('Email', models.EmailField(max_length=254)),
                ('Phone_Number', models.CharField()),
                ('Father_Name', models.CharField(max_length=100)),
                ('Mother_Name', models.CharField(max_length=100)),
                ('gardian_phone_number', models.IntegerField(max_length=12)),
                ('permanent_address', models.TextField(max_length=500)),
                ('Permanent_city', models.CharField(max_length=100)),
                ('permanent_state', models.CharField(max_length=100)),
                ('permanent_zip', models.IntegerField(max_length=6)),
                ('current_address', models.TextField(max_length=500)),
                ('Current_city', models.CharField(max_length=100)),
                ('current_state', models.CharField(max_length=100)),
                ('current_zip', models.IntegerField(max_length=6)),
            ],
        ),
    ]
