# Generated by Django 5.2.3 on 2025-06-23 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authAPP', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='Phone_Number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_zip',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='gardian_phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='permanent_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='permanent_zip',
            field=models.IntegerField(),
        ),
    ]
