# Generated by Django 5.2.3 on 2025-06-30 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studentAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('marks', models.IntegerField()),
                ('total_marks', models.IntegerField(default=0)),
                ('exam_date', models.DateField()),
                ('percentage', models.FloatField(default=0.0)),
                ('grade', models.CharField(max_length=2)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentAPP.student')),
            ],
        ),
    ]
